# data params
dataset: '3_core'

# model params
model: 'LRPPM'
model_type: 'tag_aware'
embedding_size: 16

# run params
rating_weight: 1
reason_weight: 0
video_weight: 1
interest_weight: 1
l2_weight: 0.0001
lr: 0.001
learner: 'adam'
weight_decay: 0
epochs: 100
batch_size: 256
top_k: 10
neg_sample_num: 1
endure_times: 3
train_type: 'bpr'
candidate_num: 100

# general params
seed: 1111
cuda: True
gpu_id: 1
checkpoint: './lrppm'